### ISSUE TITLE
Plugin returns icon name instead of the url

### ISSUE THREAD

**Issue by aivaras82** [houke/acf-icon-picker#1]
First of all, great job on the plugin.
I'm using _'Advanced Custom Fields PRO_' Version 5.5.11 and _WordPress_ Version 4.7.3.
However, I had to modify it to work for me as it was returning an icon name for me and not the url of the icon.
In _input.js_ once you select an icon (let's say **facebook**) the value for the hidden input is updated with an icon name:
"input.js"
line 5: `var val = jQuery(this).data('svg');`

"acf-icon-picker-v5.php"
line 75: `<input type="hidden" readonly="" name="acf[field_58d30f84d10e9][0][field_58d3122fd10f3][0][field_58d31235d10f4]" value="facebook">`

I didn't have much time to make a proper fix, so I've changed the code in both files like so:
"input.js"
line 5: `var val = jQuery(this).find('img').attr('src');`

"acf-icon-picker-v5.php"
```
function render_field( $field )
{
	$input_icon = ( ! empty( $field['value'] ) ) ? $field['value'] : $field['initial_value'];
	?>
	<div class="acf-icon-picker">
		<div class="acf-icon-picker__img">
			<?php
			if ( ! empty( $field['value'] ) ) {
				echo '<div class="acf-icon-picker__svg">';
				echo '<img src="' . $input_icon . '" alt=""/>';
				echo '</div>';
			} else {
				echo '<div class="acf-icon-picker__svg">';
				echo '<span class="acf-icon-picker__svg--span">&plus;</span>';
				echo '</div>';
			}
			?>
			<input type="hidden" readonly name="<?php echo esc_attr( $field['name'] ) ?>"
					       value="<?php echo esc_attr( $input_icon ) ?>"/>
		</div>
	</div>
<?php
}
```

It would be nice if this could be properly fixed, but ideally it would be nice if the value was saved as an array with an icon name and icon URL.
Other than that works perfectly fine.

**Comment by houke** [comment]
We have a helper function in our themes which works like this (we want inline svgs):
`function get_the_svg($filename) {
	$path = get_stylesheet_directory() .'/assets/img/'. $filename . '.svg';
        if ( file_exists( $path ) ) {
	    return file_get_contents($path);
	}
}
`
Now we can get the icon like this: `<?php echo get_the_svg( get_field('icon') ); ?>`

So that's why the plugin is returning the name instead of the url. However, returning an array with name and url is actually a good idea. So I'll look into that if I have some time.

**Comment by aivaras82** [comment]
Thanks for a prompt response. Now it all makes sense, however it wasn't clear from the documentation. Thanks a lot, this is really useful and well built.
