### ISSUE TITLE
How to set icons directory location to a custom plugin folder?

### ISSUE THREAD

**Issue by srikat** [houke/acf-icon-picker#10]
I am trying to set the path for the icons directory like this:

```
add_filter( 'acf_icon_path_suffix', 'acf_icon_path_suffix' );
function acf_icon_path_suffix( $path_suffix ) {
	return WP_PLUGIN_DIR . '/my-custom-functionality/assets/icons/';
}
```

This results in a few lines of warnings in the admin.

The first line has:

> Warning:  scandir(/Users/sridharkatakam/Sites/oxygen/atomic/wp-content/plugins/acf-icon-picker//Users/sridharkatakam/Sites/oxygen/atomic/wp-content/plugins/my-custom-functionality/assets/icons/): failed to open dir: No such file or directory in /Users/sridharkatakam/Sites/oxygen/atomic/wp-content/plugins/acf-icon-picker/fields/acf-icon-picker-v5.php on line 42

Any ideas?

Same issue with

```
add_filter( 'acf_icon_path_suffix', 'acf_icon_path_suffix' );
function acf_icon_path_suffix( $path_suffix ) {
	return plugin_dir_url( __FILE__ ) . 'assets/icons/';
}
```

as well.

**Comment by houke** [comment]
Right now, that isn't possible. We expect the icons to live in your theme, so you should return a relative folder from inside your theme. For example

```
add_filter( 'acf_icon_path_suffix', function( $path_suffix ) {
	return 'assets/img/sprite/';
} );
```
would load the icons from the assets/img/sprite folder in your theme folder.

If you want to change this to a complete different location and know your way around php, you should edit around this line: https://github.com/houke/acf-icon-picker/blob/ec182b09b1c4d45c8adaf4da96cb21be87dab23b/fields/acf-icon-picker-v5.php#L29

**Comment by srikat** [comment]
Thanks for the reply.

That is unfortunate. The functionality offered here is in plugin territory and the icons should live in a plugin as well imo.

Also, with newer technologies like [Oxygen](https://oxygenbuilder.com) themes are a thing of past.

**Comment by houke** [comment]
Feel free to make a pull request with the solution :)
Otherwise, I'll have a look at this next month.
