### ISSUE TITLE
Not recognized in gutenberg as field

### ISSUE THREAD

**Issue by hozakjaf** [houke/acf-icon-picker#15]
When selecting a new icon, Gutenberg doesn't directly apply the changes i've made. I have to update another field to prevent this from happening.

**Comment by houke** [comment]
I am aware of Gutenberg issue, this is being tracked here: https://github.com/houke/acf-icon-picker/issues/12. I am closing this one, to make sure there's one global Gutenberg topic.

Also a WIP here: https://github.com/houke/acf-icon-picker/pull/14, feel free to join in :)
