### ISSUE TITLE
I got this error at frontend and backend 

### ISSUE THREAD

**Issue by adi88nugroho** [houke/acf-icon-picker#18]
Hi,

I got this error at frontend and backend 

`
Message:
scandir(/customers/f/c/7/pinotag.com/httpd.www/wp-content/plugins/acf-icon-picker-master/assets/img/icons/): failed to open dir: No such file or directory 

Location:
 -wp-content/plugins/acf-icon-picker-master/fields/acf-icon-picker-v5.php:42scandir()wp-content/plugins/acf-icon-picker-master/fields/acf-icon-picker-v5.php:42acf_field_icon_picker->__construct()wp-content/plugins/acf-icon-picker-master/fields/acf-icon-picker-v5.php:104acf_plugin_icon_picker->include_field_types()wp-includes/class-wp-hook.php:288do_action('acf/include_field_types')wp-content/plugins/advanced-custom-fields/acf.php:265ACF->init()wp-includes/class-wp-hook.php:288do_action('init')wp-settings.php:523`

`Message:
scandir(): (errno 2): No such file or directory

Location:
wp-content/plugins/acf-icon-picker-master/fields/acf-icon-picker-v5.php:42
`

`Message:
array_diff(): Expected parameter 1 to be an array, bool given

Location:
wp-content/plugins/acf-icon-picker-master/fields/acf-icon-picker-v5.php:42
`
`
Message:
Invalid argument supplied for foreach()

Location:
wp-content/plugins/acf-icon-picker-master/fields/acf-icon-picker-v5.php:43
`

**Comment by houke** [comment]
Did you add a filter to your theme? As `icons/` isn't the default folder of this plugin. (If you don't add any filters, the icons should be stored in the `assets/img/acf/` folder of this plugin
