### ISSUE TITLE
Icon preview not working

### ISSUE THREAD

**Issue by negru13** [houke/acf-icon-picker#22]
Hi, what could be the problem?
I have ACF Pro 5.9.3
WP 5.6 
![Screenshot_7](https://user-images.githubusercontent.com/63023292/102728012-0ff3e500-4332-11eb-84a2-d2f045bde076.png)

Thank you.

**Comment by houke** [comment]
Are your icons white, then they're there but you can't see them. Either make your icons another color, of edit the plugin files to give the modal a bg color. 

Or are you seeing not found warnings in your console (open the console, go to the network tab & then open the popup)?
