### ISSUE TITLE
Incompatible with Internet Explorer 11

### ISSUE THREAD

**Issue by ajreading** [houke/acf-icon-picker#24]
The plugin uses template literals, or backtick strings (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) within `assets/js/input.js` which means that it causes JavaScript errors when accessing the site from IE11. This unfortunately breaks many of WordPress' admin screens which depend upon JavaScript functionality.

I appreciate that WordPress are currently considering dropping IE11 support, but that may still be up to a year away.

It would be a relatively simple fix to support IE11 by replacing the backticks with some quotes and concatenation instead.

**Comment by houke** [comment]
Yes, this plugin was not designed with old browsers in mind as I've dropped IE11 support for a while now. I might add this when I release a new update, but I've not planned one for the foreseeable future.

Feel free to submit a PR though :)

**Comment by ajreading** [comment]
Thanks. I've submitted a PR #25

**Comment by klaudiomilankovic** [comment]
Closing due to not needed support for IE11
