### ISSUE TITLE
Search filter

### ISSUE THREAD

**Issue by klaudiomilankovic** [houke/acf-icon-picker#3]
Hi, I've just tested out your plugin and it works like a charm in a project. I will definitely continue using it. 

I've added a slight upgrade to this plugin, a search filter where you can filter the icons by name when choosing them. If you add me as a contributor I can push my code to a separate branch and make a pull request for you to see and possibly integrate this change.

**Comment by houke** [comment]
You should have an invite

**Comment by klaudiomilankovic** [comment]
Thanks man. I have made a PR , please review and merge if you think it's OK.
