### ISSUE TITLE
Forces you to pick an icon

### ISSUE THREAD

**Issue by JiveDig** [houke/acf-icon-picker#5]
No way to close the modal after it pops up. Kind of confusing for the user, and sometimes may not need an icon.

Otherwise this a nice little field type!

**Comment by JiveDig** [comment]
Just noticed the "Remove" button. That helps, but still would be nice to have a close button on the modal itself.

**Comment by klaudiomilankovic** [comment]
Hey, thanks, I will add the button for closing.

**Comment by klaudiomilankovic** [comment]
@JiveDig I've added the close option on the modal itself.

**Comment by JiveDig** [comment]
Good stuff! Works well. Nice improvement :)
