### ISSUE TITLE
Problem with hypen in .svg filename when filtering

### ISSUE THREAD

**Issue by marcelpietsch** [houke/acf-icon-picker#7]
I've uploaded several icons the my icon folder. Some of them have hyphens in them like account-check.svg, others do not. When I use the "Start typing to filter icons" function, the icons with hyphens are showing up as broken urls. That happens because the file path is now account%20check.svg instead of account-check.svg.

Hopefully you're able to reproduce this, otherwise let me know if you need more details.

Note: I've set a custom assets folder using the filter function.

`    add_filter( 'acf_icon_path_suffix', 'acf_icon_path_suffix' );
    function acf_icon_path_suffix( $path_suffix ) {
        return 'img/icons/';
    }`

![image](https://user-images.githubusercontent.com/12413778/41095646-60affd00-6a52-11e8-8b9e-2136ec2a5520.png)

**Comment by houke** [comment]
This has been fixed with the latest update
