### ISSUE TITLE
Nearly unresponsive when used with large collection of icons (~10'000 icons)

### ISSUE THREAD

**Issue by idflood** [houke/acf-icon-picker#8]
A client purchased the icon pack from https://streamlineicons.com/ , but when opening the picker modal the browser become unresponsive until the modal is closed (scrolling happend 4 or more seconds later, …).

(I will try to propose an alternative script which lazy load/display the icons)

**Comment by houke** [comment]
Thanks for the performance update! We've never used that many icons, so never had that issue ;).

**Comment by idflood** [comment]
@houke tanks for the merge : ) I will probably come back with another merge request later with some small tweaks and fine tuning. And thanks for the plugin, it is incredibly useful 👍
